version: "3.8"
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile # Production Dockerfile
    ports:
      - "4001:4001" # Map local port 4001 to container port 4001
    env_file: ./src/configs/.env.production # Production environment variables
    command: ["node", "server.js"] # Start the built app
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=smey09
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
